(cl:in-package mtt_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID_1-VAL
          ID_1
          CLASS_1-VAL
          CLASS_1
          POSITION_1-VAL
          POSITION_1
          ID_2-VAL
          ID_2
          CLASS_2-VAL
          CLASS_2
          POSITION_2-VAL
          POSITION_2
          ID_3-VAL
          ID_3
          CLASS_3-VAL
          CLASS_3
          POSITION_3-VAL
          POSITION_3
          ID_4-VAL
          ID_4
          CLASS_4-VAL
          CLASS_4
          POSITION_4-VAL
          POSITION_4
          ID_5-VAL
          ID_5
          CLASS_5-VAL
          CLASS_5
          POSITION_5-VAL
          POSITION_5
))